Feature/chatbot
D11ko/NIX_java_education_Petrenko_Dmytro pull request #2
Opened 2021-10-14 12:16 UTC by D11ko

2021-10-14 17:32 UTC, maxsomochkin requested changes

2021-10-14 17:32 UTC, maxsomochkin commented on src/nix/education/java/chatbot/ChatBot.java
> +        Scanner scanner1 = new Scanner(System.in);
Используй один scanner  в коде и вынеси его инициализацию  первой строкой в методе

2021-10-14 17:32 UTC, maxsomochkin commented on src/nix/education/java/chatbot/ChatBot.java
> +        System.out.println("Goodbye, have a nice day!");
не разрывай логику лучше будет, когда строку 
System.out.println("Goodbye, have a nice day!");
поместишь перед break; 48 строкой

2021-10-14 17:32 UTC, maxsomochkin commented on src/nix/education/java/chatbot/ChatBot.java
> +            System.out.println("Try again");
строку System.out.println("Try again"); лучше завернуть в else

2021-10-16 14:26 UTC, asrubel approved these changes

2021-10-21 18:23 UTC, merged